vich_uploader:
    db_driver: orm
    metadata:
        type: attribute

    mappings:
       participant_image:
           uri_prefix: images/participants
           upload_destination: '%kernel.project_dir%/public/images/participants'
         