controllers:
    resource: ../src/Controller/
    type: attribute


login:
    path: /api/login
    controller: App\Controller\SecurityController::login

# home:
#     path: /
#     controller: App\Controller\MainController::index

# login:
#     path: /login
#     controller: App\Controller\MainController::index
